#!/usr/bin/env bash

temp_timestamp=`date "+%Y%m%d"`
temp_role=$(aws sts assume-role \
		--role-arn "$@" \
		--duration-seconds 3600 \
		--role-session-name "${LOGNAME}_${temp_timestamp}")

unset AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN AWS_SECURITY_TOKEN

export AWS_ACCESS_KEY_ID=$(echo $temp_role | jq .Credentials.AccessKeyId | xargs)
export AWS_SECRET_ACCESS_KEY=$(echo $temp_role | jq .Credentials.SecretAccessKey | xargs)
export AWS_SESSION_TOKEN=$(echo $temp_role | jq .Credentials.SessionToken | xargs)

